[package]
name = "week1"
version = "0.1.0"
edition = "2021"

[dependencies]
expand = "0.3.0"
actix-web = "4"
sqlx = { version = "0.7", features = ["macros", "runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
